### ISSUE TITLE
Organizar las clases y los tests en paquetes

### ISSUE THREAD

**Issue by faloi** [jvillarejo/elSuperArchiRepoDDS#10]
La verdad que no le di demasiada bola a esto. No estaria de mas organizar los tests y las clases en los mismos paquetes y seguir algun criterio coherente y consistente.

**Comment by ClaraAllende** [comment]
ahora lo veo, pero la verdad mucho no me calienta xD

**Comment by jvillarejo** [comment]
Idem...
