### ISSUE TITLE
Implementar las compras

### ISSUE THREAD

**Issue by ClaraAllende** [jvillarejo/elSuperArchiRepoDDS#5]
Esto faltaría hacerse del lado de nuestro model, del lado de lanchita, Juani ya hizo la parte de mandar el mensaje en el wrapper.

**Comment by ClaraAllende** [comment]
ariel agarra este issue. hay que agregarlo como collaborator

**Comment by aperpinal** [comment]
no se como asignarmelo, pero este lo hago yo. aviso asi no nos pisamos

**Comment by aperpinal** [comment]
pollo o quien corresponda necesito q me asigne permisos q no puedo pushear

**Comment by aperpinal** [comment]
como seria la onda del comprar asientos? el asiento tiene un metodo comprar q llama al AerolineaLanchitaWrapper pero desde el test se lo esta puenteando xq hace directamente AerolineaLanchitaWrapper.comprarAsiento. Alguien me podria explicar bien como seria este flujo?

**Comment by ClaraAllende** [comment]
pushea a tu branch y despues mergeamos.

**Comment by ClaraAllende** [comment]
la cosa es así (perdón que contesto recién ahora, estaba en clase): El caso de uso iniciaría en la agencia, cuando le mandan el mensaje comprar. Ese comprar debería llamar al comprar del asiento y de ahí al wrapper (que es el que habla con lanchita para hacer el tema de las compras).
Lo que hay que completar es el tema de la lógica de lo que pasa en la agencia cuando se compra un asiento, porque del lado de lanchita solo se actualiza la disponibilidad, pero lo demás se hace del lado de nuestro model.
